<?php

/**
 * This file is automatically generated. Use 'arc liberate' to rebuild it.
 *
 * @generated
 * @phutil-library-version 2
 */
phutil_register_library_map(array(
  '__library_version__' => 2,
  'class' => array(
    'BaseGeekieTestEngine' => 'unit/BaseGeekieTestEngine.php',
    'ESLintLinter' => 'lint/ESLintLinter.php',
    'JestTestEngine' => 'unit/JestTestEngine.php',
    'SherminateTestEngine' => 'unit/SherminateTestEngine.php',
  ),
  'function' => array(),
  'xmap' => array(
    'BaseGeekieTestEngine' => 'ArcanistUnitTestEngine',
    'ESLintLinter' => 'ArcanistExternalLinter',
    'JestTestEngine' => 'BaseGeekieTestEngine',
    'SherminateTestEngine' => 'BaseGeekieTestEngine',
  ),
));
